CorinneBundle\Entity\Objet:
    type: entity
    table: null
    repositoryClass: CorinneBundle\Repository\ObjetRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        source:
            type: string
            length: 255
        alt:
            type: string
            length: 255
        definition:
            type: text
        slider:
            type: boolean
    manyToOne:
        product:
            targetEntity: CorinneBundle\Entity\SousCategorie
            inversedBy: objet
            joinColumn:
                name: souscat_id
                referencedColumnName: id
    manyToOne:
        product:
            targetEntity: CorinneBundle\Entity\Categorie
            inversedBy: objet
            joinColumn:
                name: cat_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
