CorinneBundle\Entity\Presse:
    type: entity
    table: null
    repositoryClass: CorinneBundle\Repository\PresseRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        source:
            type: string
            length: 255
        alt:
            type: string
            length: 255
    oneToOne:
        events:
            targetEntity: CorinneBundle\Entity\Event
            joinColumn:
                name: event_id
                referencedColumnName: id
    lifecycleCallbacks:
        prePersist: [ preUpload, setCreatedAtValue, setExpiresAtValue ]
        preUpdate: [ preUpload, setUpdatedAtValue ]
        postPersist: [ upload ]
        postUpdate: [ upload ]
        postRemove: [ removeUpload ]

