objet_index:
    path:     /
    defaults: { _controller: "CorinneBundle:Objet:index" }
    methods:  GET

objet_show:
    path:     /{id}/show
    defaults: { _controller: "CorinneBundle:Objet:show" }
    methods:  GET

objet_new:
    path:     /new
    defaults: { _controller: "CorinneBundle:Objet:new" }
    methods:  [GET, POST]

objet_edit:
    path:     /{id}/edit
    defaults: { _controller: "CorinneBundle:Objet:edit" }
    methods:  [GET, POST]

objet_delete:
    path:     /{id}/delete
    defaults: { _controller: "CorinneBundle:Objet:delete" }
    methods:  DELETE
