corinne_homepage:
    path:     /
    defaults: { _controller: CorinneBundle:Default:index }

corinne_parcour:
    path:     /parcour
    defaults: { _controller: CorinneBundle:Default:parcours }

corinne_creation:
    path:     /creation
    defaults: { _controller: CorinneBundle:Default:creation }

corinne_ecolabel:
    path:     /ecolabel
    defaults: { _controller: CorinneBundle:Default:ecolabel }

corinne_contact:
    path:     /contact
    defaults: { _controller: CorinneBundle:Default:contact }

corinne_atelier:
    path:     /atelier
    defaults: { _controller: CorinneBundle:Default:atelier }

corinne_access:
    path:     /access
    defaults: { _controller: CorinneBundle:Default:access }

corinne_presse:
    path:     /presse
    defaults: { _controller: CorinneBundle:Default:presse }

