corinne_user:
    prefix:   /
    resource: routing/user.yml

corinne_categorie:
    resource: "@CorinneBundle/Resources/config/routing/categorie.yml"
    prefix:   /admin/categorie

corinne_souscategorie:
    resource: "@CorinneBundle/Resources/config/routing/souscategorie.yml"
    prefix:   /admin/souscategorie

corinne_objet:
    resource: "@CorinneBundle/Resources/config/routing/objet.yml"
    prefix:   /admin/objet

corinne_presse:
    resource: "@CorinneBundle/Resources/config/routing/presse.yml"
    prefix:   /admin/presse

corinne_event:
    resource: "@CorinneBundle/Resources/config/routing/event.yml"
    prefix:   /admin/event

corinne_ecolabel:
    resource: "@CorinneBundle/Resources/config/routing/ecolabel.yml"
    prefix:   /admin/ecolabel

#corinne_contact:
#    resource: "@CorinneBundle/Resources/config/routing/contact.yml"
#    prefix:   /admin/contact

corinne_admin:
    prefix: /
    resource: routing/admin.yml


contact_new:
    path:     /new
    defaults: { _controller: "CorinneBundle:Contact:new" }
    methods:  [GET, POST]
