CorinneBundle\Entity\Objet:
    properties:
        source:
            - File:
                maxSize: 3512k
                mimeTypesMessage: merci de chargez une image valide
                mimeTypes: [image/*]
        imageFile:
            - File:
                maxSize: 3512k
                mimeTypesMessage: merci de chargez une image valide
                mimeTypes: [image/*]